language: python
sudo: false

cache:
  directories:
    - $HOME/.pip-cache/

matrix:
  include:
    - python: "2.6"
      env: TOXENV=py26 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "2.7"
      env: TOXENV=py27 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "3.2"
      env: TOXENV=py32 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "3.3"
      env: TOXENV=py33 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "3.4"
      env: TOXENV=py34 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "3.5"
      env: TOXENV=py35 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "pypy"
      env: TOXENV=pypy PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "pypy3"
      env: TOXENV=pypy3 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "2.7"
      env: TOXENV=docs PIP_DOWNLOAD_CACHE=$HOME/.pip-cache

install:
- git config --global user.email "travisci@jasonantman.com"
- git config --global user.name "travisci"
- pip install tox
- pip install codecov
- pip freeze
- virtualenv --version
script:
  - tox -r

after_success:
  - codecov

notifications:
  email:
    on_success: always
    on_failure: always
  pushover:
    users:
    - secure: "Raaj3Kp0c8Rf4sYMpBvgR+utO/Kht+wHvIMGDjq/+YFYoycm7yJhZojSanPhxmyRgE6wiKTwIsTe1J2EWWG20rHF6M5oAYNAc1z5iClab267fmFjPS/iP7/LJAvipxlQsuRpzatdhuvnM5wxFzbobRlUX1Z2vwb/QFzNN3NoVfQlrEmbkOtdXjq6pFgSlHSn/AhA4BF4uUe8GAB7Ifuvqdc9lAt7SqcXUIV0kExPBUUoNRA6HfTxoNjxigP6htJK+rMw8WkKRQTl12z22vgKTcrmiB5uuISBTj5fp5cXo6hJPBDUHUokVQdIeq2p9hbi/CWXQWEFIZw7lVVgHg32yiIP2ghd3VjXXg2YLKusukqFuNoa2ZSIW1UMm41sL80hv7B23fNae6e6qz+DReUpPpDP8woSFfJR1810+D9ete+XusVny2vLzxLAlC8sczPCh7oH7VoHGa6kVdLrl9h/dFcXKrZgZpkTp/WVzp8gThkbV3+eNSUCjs+0dRelQrwnw7UkwZx8MzWPA3VKzAJueshv07nkdAF7uLHhH6ZhPUkukfuxLpYO3MEYqyAFdogs8tP0MVolI2wjJ9C712n1iIHHEGWATE3spYqCKaU5IYjSgNoGBsUwf0R/kpLgKEhOvXzFfHHta+ivBKVqpRGq+e54h4BgqJHwdZkCPLrRY5c="
    api_key:
      secure: "SsXJyIMDR1Y0bUGeJS+NlfWEbexGiFeez9H2IrL4xO68J1euByNHcXDsWsuakpdfr8/dvB0USkq6YaE2YCk73uBscJr8yERS9N1swL8CqsMRr2+trXtpU0cVDgNRsWi4nU+rTarwFvGltrdIfRKmF6YKizOie5CzzTMrEp1V9gutGkpShqIK/ByQKqqeKa2dfoah/9aFPs0RJYXCtLPKcKzLKEfJnetP80NLEPZDjRsVfMWsquv9Vim83ySZElRvudj5m21reewktApr5HE4/WQQBp73n93cBA0YJdD8+B0tNQoNc6eevjLr1c3PFCVzQByLGCJhDAYtfkkJQbETUzrKmQV8AVHKaXlfFEEtbBHjavfuZsBouEXMhTEQKQTbyO2Q3XmYoXMDhFzWzBfug6sS0LKAnt/Ei24oLHTr6HxRb2fxDfylsg6b2ymri0+/bejiQ0xH70qo5Aq6xUbNyhsxMJmDrVwQL4a331ps9dWOod01IrTvZ0pQlMFvmjtjUg6nUb1Oxy6wzzK1j/LqILS3Eo0Muaoj8Umi6xCsSX1g6gRsKfktjwTlvEkyHVySM6gT82OPVfi/NUP0ETn9l6C7FMtcSu4APWqPwdkmx/TH4a32V+lMdwGuCheQEG7EmQuWUetSd1dPrynt/3u7KpJtgSC2Fi/du3T4IgCBgbY="
branches:
  except:
    - "/^noci-.*$/"
